--INSERT INTO role (id, name) VALUES 
--(1, 'ROLE_ADMIN'),
--(2, 'ROLE_USER');
--
--INSERT INTO usuario (matricula, email, nome, senha) VALUES 
--('1', 'admin@gmail.com', 'Admin', '$2a$10$hKDVYxLefVHV/vtuPhWD3OigtRyOykRLDdUAp80Z1crSoS1lFqaFS'),
--('2', 'usuario@gmail.com', 'Usuario', '$2a$10$ByIUiNaRfBKSV6urZoBBxe4UbJ/sS6u1ZaPORHF9AtNWAuVPVz1by');
--
--insert into usuario_role(usuario_matricula, role_id) values
--(1,1),
--(1,2),
--(2,2);